info:
  contact: {}
paths: {}
securityDefinitions:
  Authorization:
    description: Please input prefix "Bearer " and your access token.
    in: header
    name: Authorization
    type: apiKey
  X-OPENAPI-JWT:
    description: Please input your customer id. (works only in dev environment)
    in: header
    name: X-OPENAPI-JWT
    type: apiKey
swagger: "2.0"
